// const callback = () => console.log('abc')
// const observer = new IntersectionObserver(callback)

// observer.observe(document.querySelector('#root'))
// observer.observe(document.querySelector('#abc'))
// observer.observe(document.querySelector('#rt'))
// observer.observe(document.querySelector('#oot'))
// observer.observe(document.querySelector('#t'))
// observer.observe(document.querySelector('#123'))
// observer.disconnect()
// observer.unobserve(document.querySelector('#root'))
